import { useState } from 'react'
import Modal from './Modal.jsx'
import { AI_PROVIDERS, generateAIPhoto, saveAISettings } from '../lib/aiImage.js'

// AI engine settings: pick the image provider and (for paid ones) store an API
// key. Everything stays in this browser's localStorage — keys are only ever
// sent to the provider itself.

export default function AISettings({ settings, onChange, onClose }) {
  const [provider, setProvider] = useState(settings.provider)
  const [keys, setKeys] = useState({ ...settings.keys })
  const [testState, setTestState] = useState(null) // null | 'busy' | {ok, message, image?}

  const persist = (nextProvider = provider, nextKeys = keys) => {
    const next = { provider: nextProvider, keys: nextKeys }
    saveAISettings(next)
    onChange(next)
  }

  const pick = (id) => {
    setProvider(id)
    setTestState(null)
    persist(id, keys)
  }

  const setKey = (id, value) => {
    const nextKeys = { ...keys, [id]: value }
    setKeys(nextKeys)
    persist(provider, nextKeys)
  }

  const runTest = async () => {
    setTestState('busy')
    try {
      const { dataUrl, provider: used } = await generateAIPhoto({
        prompt:
          'Professional commercial photograph of a modern office desk with a laptop, soft window light, hyper-realistic, photorealistic, no text',
        width: 512,
        height: 512,
        seed: Math.floor(Math.random() * 1e6),
        settings: { provider, keys },
      })
      const label = AI_PROVIDERS.find((p) => p.id === used)?.label || used
      setTestState({ ok: true, message: `Working — photo generated by ${label}.`, image: dataUrl })
    } catch (err) {
      setTestState({ ok: false, message: err.message })
    }
  }

  return (
    <Modal title="AI image engine" onClose={onClose}>
      <p className="mb-4 text-sm leading-relaxed text-white/75">
        Real photos for your posts are generated by the engine you pick here. The free engine works
        with no setup. Your API keys are stored <strong>only in this browser</strong> and sent only
        to the provider you choose.
      </p>

      <div className="space-y-2.5">
        {AI_PROVIDERS.map((p) => {
          const active = provider === p.id
          return (
            <div
              key={p.id}
              className={`rounded-xl border p-3.5 transition-all ${
                active ? 'border-teal/50 bg-teal/[0.06]' : 'border-white/10 bg-white/[0.02]'
              }`}
            >
              <button type="button" className="flex w-full items-center gap-3 text-left" onClick={() => pick(p.id)}>
                <span
                  className={`grid h-4 w-4 shrink-0 place-items-center rounded-full border ${
                    active ? 'border-teal' : 'border-white/30'
                  }`}
                >
                  {active && <span className="h-2 w-2 rounded-full bg-teal" />}
                </span>
                <span className="flex-1">
                  <span className="block text-sm font-semibold text-white">{p.label}</span>
                  <span className="block text-xs text-white/60">{p.tagline}</span>
                </span>
                {!p.needsKey && (
                  <span className="rounded-md bg-teal/15 px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-teal-soft">
                    Free
                  </span>
                )}
              </button>
              {p.needsKey && active && (
                <input
                  type="password"
                  className="field mt-3"
                  autoComplete="off"
                  value={keys[p.id] || ''}
                  onChange={(e) => setKey(p.id, e.target.value)}
                  placeholder={`${p.label.split('·')[0].trim()} API key (${p.keyPlaceholder})`}
                />
              )}
            </div>
          )
        })}
      </div>

      <div className="mt-5 flex items-center gap-3">
        <button type="button" className="btn-teal" disabled={testState === 'busy'} onClick={runTest}>
          {testState === 'busy' ? (
            <>
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-teal border-t-transparent" />
              Testing… can take ~20 s
            </>
          ) : (
            'Test generation'
          )}
        </button>
        <span className="text-xs text-white/50">Generates one small test photo with the engine above.</span>
      </div>

      {testState && testState !== 'busy' && (
        <div
          className={`mt-4 flex items-center gap-3 rounded-xl border px-4 py-3 ${
            testState.ok
              ? 'border-teal/30 bg-teal/[0.07] text-teal-soft'
              : 'border-red-400/25 bg-red-400/10 text-red-200'
          }`}
        >
          {testState.image && (
            <img src={testState.image} alt="Test result" className="h-14 w-14 rounded-lg object-cover" />
          )}
          <p className="text-sm">{testState.message}</p>
        </div>
      )}
    </Modal>
  )
}
